export function generateDocsArchitecture(name: string): string {
	return `# Architecture

${name} is a full-stack web application built as a pnpm monorepo using Turborepo. The frontend is a Next.js 16 app with React 19, the backend runs on Convex (serverless functions + database), and authentication is handled by Better Auth running inside Convex as a component.

## Directory Structure

\`\`\`
${name}/
├── apps/web/                    # Main Next.js application
│   ├── app/
│   │   ├── (marketing)/         # Public marketing pages
│   │   ├── (auth)/              # Login/authentication
│   │   ├── (app)/               # Authenticated user pages
│   │   └── api/                 # API routes
│   ├── components/              # React components
│   ├── convex/                  # Convex schema, functions, and seed
│   ├── lib/                     # Shared utilities
│   ├── services/                # Data access layer
│   └── workflows/               # Vercel Workflows
├── packages/
│   └── ui/                      # Shared UI components (shadcn/ui)
├── scripts/                     # Setup and harness scripts
└── docs/                        # Project documentation
\`\`\`

## Data Flow

\`\`\`
Browser → Next.js RSC → services/ → Convex query/mutation → Convex DB → response
\`\`\`

Server components create promises via the service layer, pass them to client components, and client components unwrap them with React's \`use()\` hook inside a Suspense boundary. All database access goes through \`services/\` files—components never call Convex directly.

## Auth Flow

\`\`\`
Browser → Better Auth client → /api/auth/[...all] proxy → Convex HTTP action → betterAuth component
\`\`\`

Better Auth runs inside Convex as the \`@convex-dev/better-auth\` component. The Next.js API route at \`/api/auth/[...all]\` proxies requests to the Convex HTTP action, which delegates to the Better Auth component for session management, OTP verification, and user creation.

## Workflow Flow

\`\`\`
Trigger → POST /api/workflow → Vercel Workflow → "use step" functions → SSE progress via /api/workflow-progress/[runId]
\`\`\`

Vercel Workflows handle long-running operations. Each I/O operation inside a workflow must be wrapped in a function marked with \`"use step"\` so the workflow engine can track, retry, and resume operations. Progress is streamed to the client via Server-Sent Events.

## Key Invariants

- **Never call the database from components.** All data access goes through the \`services/\` layer.
- **\`_generated/\` is machine-generated.** Never edit files in \`convex/_generated/\`. They are regenerated by \`npx convex dev\`.
- **\`convex/schema.ts\` is the schema source of truth.** The database schema is defined here and deployed to Convex. All queries and mutations must align with this schema.
- **Route groups enforce access patterns.** \`(marketing)\` pages are public, \`(auth)\` pages handle login, and \`(app)\` pages require authentication.
`;
}
