export function generateDocsArchitecture(name: string): string {
	return `# Architecture

${name} is a full-stack web application built as a pnpm monorepo using Turborepo. The frontend is a Next.js 16 app with React 19, the backend runs on Convex (serverless functions + database), and authentication is handled by Better Auth running inside Convex as a component.

## Directory Structure

\`\`\`
${name}/
├── apps/web/                    # Main Next.js application
│   ├── app/
│   │   ├── (marketing)/         # Public marketing pages
│   │   ├── (auth)/              # Login/authentication
│   │   ├── (app)/               # Authenticated user pages
│   │   └── api/                 # API routes
│   ├── components/              # React components
│   ├── convex/                  # Convex schema, functions, and seed
│   └── lib/                     # Shared utilities
├── scripts/                     # Setup and harness scripts
└── docs/                        # Project documentation
\`\`\`

## Data Flow

\`\`\`
Browser → Convex React hooks (useQuery/useMutation) → Convex functions → Convex DB → reactive update
\`\`\`

Client components use \`useQuery\` for reactive reads and \`useMutation\` for writes. Data flows through Convex functions defined in \`convex/\`. Queries automatically re-render when underlying data changes.

## Auth Flow

\`\`\`
Browser → Better Auth client → /api/auth/[...all] proxy → Convex HTTP action → betterAuth component
\`\`\`

Better Auth runs inside Convex as the \`@convex-dev/better-auth\` component. The Next.js API route at \`/api/auth/[...all]\` proxies requests to the Convex HTTP action, which delegates to the Better Auth component for session management, OTP verification, and user creation.

## Key Invariants

- **\`_generated/\` is machine-generated.** Never edit files in \`convex/_generated/\`. They are regenerated by \`npx convex dev\`.
- **\`convex/schema.ts\` is the schema source of truth.** The database schema is defined here and deployed to Convex. All queries and mutations must align with this schema.
- **Route groups enforce access patterns.** \`(marketing)\` pages are public, \`(auth)\` pages handle login, and \`(app)\` pages require authentication.
`;
}
