export function generateSetupScript(
	useDocker: boolean,
	projectName: string,
): string {
	return `#!/usr/bin/env bash
set -e

# =============================================================================
# Project Setup Script
# Generated by Hatch CLI
# =============================================================================

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# Project configuration (embedded at generation time)
PROJECT_NAME="${projectName}"
USE_DOCKER=${useDocker ? "true" : "false"}

# State tracking file for idempotency
STATE_FILE=".setup-state"

# =============================================================================
# Helper Functions
# =============================================================================

print_header() {
  echo ""
  echo "========================================"
  echo -e "\${BLUE}\$1\${NC}"
  echo "========================================"
  echo ""
}

print_step() {
  echo -e "\${BLUE}→\${NC} \$1"
}

print_success() {
  echo -e "\${GREEN}✓\${NC} \$1"
}

print_warning() {
  echo -e "\${YELLOW}⚠\${NC} \$1"
}

print_error() {
  echo -e "\${RED}✗\${NC} \$1"
}

# State management for idempotency
mark_completed() {
  echo "\$1" >> "\$STATE_FILE"
}

is_completed() {
  [[ -f "\$STATE_FILE" ]] && grep -q "^\$1$" "\$STATE_FILE"
}

# =============================================================================
# Step 1: Check Prerequisites
# =============================================================================

check_prerequisites() {
  print_header "Checking Prerequisites"

  local missing=()

  # Check gh CLI
  if command -v gh &> /dev/null; then
    print_success "GitHub CLI (gh) installed"
  else
    missing+=("gh")
    print_error "GitHub CLI (gh) not installed"
  fi

  # Check vercel CLI
  if command -v vercel &> /dev/null; then
    print_success "Vercel CLI installed"
  else
    missing+=("vercel")
    print_error "Vercel CLI not installed"
  fi

  # Check supabase CLI (only if not using Docker)
  if [[ "\$USE_DOCKER" != "true" ]]; then
    if command -v supabase &> /dev/null; then
      print_success "Supabase CLI installed"
    else
      missing+=("supabase")
      print_error "Supabase CLI not installed"
    fi
  fi

  # Check jq (needed for parsing JSON)
  if command -v jq &> /dev/null; then
    print_success "jq installed"
  else
    missing+=("jq")
    print_error "jq not installed"
  fi

  if [[ \${#missing[@]} -gt 0 ]]; then
    echo ""
    print_error "Missing required tools: \${missing[*]}"
    echo ""
    echo "Install them with:"
    for tool in "\${missing[@]}"; do
      case \$tool in
        gh)
          echo "  brew install gh"
          ;;
        vercel)
          echo "  npm i -g vercel"
          ;;
        supabase)
          echo "  brew install supabase/tap/supabase"
          ;;
        jq)
          echo "  brew install jq"
          ;;
      esac
    done
    exit 1
  fi

  print_success "All prerequisites satisfied"
}

# =============================================================================
# Step 2: Authenticate with GitHub
# =============================================================================

auth_github() {
  print_header "GitHub Authentication"

  # Check if already authenticated
  if gh auth status &> /dev/null; then
    print_success "Already authenticated with GitHub"
    return 0
  fi

  print_step "Opening browser for GitHub authentication..."
  gh auth login --web

  if gh auth status &> /dev/null; then
    print_success "GitHub authentication successful"
  else
    print_error "GitHub authentication failed"
    exit 1
  fi
}

# =============================================================================
# Step 3: Authenticate with Supabase (skipped if USE_DOCKER=true)
# =============================================================================

auth_supabase() {
  if [[ "\$USE_DOCKER" == "true" ]]; then
    print_step "Skipping Supabase authentication (Docker mode)"
    return 0
  fi

  print_header "Supabase Authentication"

  # Check if already authenticated
  if supabase projects list &> /dev/null 2>&1; then
    print_success "Already authenticated with Supabase"
    return 0
  fi

  print_step "Opening browser for Supabase authentication..."
  supabase login

  if supabase projects list &> /dev/null 2>&1; then
    print_success "Supabase authentication successful"
  else
    print_error "Supabase authentication failed"
    exit 1
  fi
}

# =============================================================================
# Step 4: Authenticate with Vercel
# =============================================================================

auth_vercel() {
  print_header "Vercel Authentication"

  # Check if already authenticated
  if vercel whoami &> /dev/null 2>&1; then
    print_success "Already authenticated with Vercel"
    return 0
  fi

  print_step "Opening browser for Vercel authentication..."
  vercel login

  if vercel whoami &> /dev/null 2>&1; then
    print_success "Vercel authentication successful"
  else
    print_error "Vercel authentication failed"
    exit 1
  fi
}

# =============================================================================
# Step 5: Create GitHub Repository
# =============================================================================

create_github_repo() {
  print_header "GitHub Repository Setup"

  # Check if remote 'origin' already exists locally
  if git remote get-url origin &> /dev/null 2>&1; then
    print_success "Git remote 'origin' already configured"
    # Verify we can access the remote
    if git ls-remote origin &> /dev/null 2>&1; then
      print_success "Remote repository accessible"
    else
      print_warning "Remote exists but may not be accessible"
    fi
    return 0
  fi

  if is_completed "github_repo"; then
    print_success "GitHub repository already created (from previous run)"
    return 0
  fi

  # Check if repo already exists on GitHub before creating
  if gh repo view "\$PROJECT_NAME" &> /dev/null 2>&1; then
    print_warning "Repository '\$PROJECT_NAME' already exists on GitHub"
    echo ""
    echo "Options:"
    echo "  1. Link to existing repository (won't push - manual sync required)"
    echo "  2. Use a different name"
    echo "  3. Cancel setup"
    echo ""
    read -p "Choice (1/2/3): " choice

    case \$choice in
      1)
        # Link to existing - DO NOT push (would overwrite remote)
        local gh_user=\$(gh api user -q .login 2>/dev/null)
        git remote add origin "https://github.com/\$gh_user/\$PROJECT_NAME.git"
        print_success "Linked to existing repository"
        print_warning "Code NOT pushed to avoid overwriting. Sync manually if needed."
        mark_completed "github_repo"
        return 0
        ;;
      2)
        read -p "Enter new repository name: " new_name
        print_step "Creating private GitHub repository: \$new_name"
        if gh repo create "\$new_name" --private --source=. --push; then
          print_success "GitHub repository '\$new_name' created and code pushed"
          mark_completed "github_repo"
        else
          print_error "Failed to create repository"
          exit 1
        fi
        return 0
        ;;
      3)
        print_step "Cancelled by user"
        exit 1
        ;;
      *)
        print_error "Invalid choice"
        exit 1
        ;;
    esac
  fi

  # Safe to create - repo doesn't exist
  print_step "Creating private GitHub repository: \$PROJECT_NAME"

  if gh repo create "\$PROJECT_NAME" --private --source=. --push; then
    print_success "GitHub repository created and code pushed"
    mark_completed "github_repo"
  else
    print_error "Failed to create repository"
    echo ""
    echo "This might happen if:"
    echo "  - Repository name is already taken"
    echo "  - You don't have permission to create repos"
    echo ""
    read -p "Would you like to link to an existing repository? (y/N) " link_existing
    if [[ "\$link_existing" == [yY] ]]; then
      read -p "Enter repository (e.g., username/repo): " repo_name
      git remote add origin "https://github.com/\$repo_name.git"
      git push -u origin main 2>/dev/null || git push -u origin master 2>/dev/null || true
      mark_completed "github_repo"
    else
      exit 1
    fi
  fi
}

# =============================================================================
# Step 6: Create Supabase Project (skipped if USE_DOCKER=true)
# =============================================================================

create_supabase_project() {
  if [[ "\$USE_DOCKER" == "true" ]]; then
    print_step "Skipping Supabase project creation (Docker mode)"
    return 0
  fi

  print_header "Supabase Project Setup"

  # Check if already linked
  if [[ -f ".supabase/.project-ref" ]]; then
    local existing_ref=\$(cat .supabase/.project-ref)
    print_success "Already linked to Supabase project: \$existing_ref"
    return 0
  fi

  if is_completed "supabase_project"; then
    print_success "Supabase project already configured (from previous run)"
    return 0
  fi

  # Check if project name already exists in user's Supabase account
  local existing_project=\$(supabase projects list --json 2>/dev/null | jq -r ".[] | select(.name == \\"\$PROJECT_NAME\\") | .id" 2>/dev/null || echo "")

  if [[ -n "\$existing_project" ]]; then
    print_warning "Supabase project '\$PROJECT_NAME' already exists (ref: \$existing_project)"
    echo ""
    echo "Options:"
    echo "  1. Link to existing project"
    echo "  2. Create with different name"
    echo "  3. Cancel setup"
    echo ""
    read -p "Choice (1/2/3): " choice

    case \$choice in
      1)
        PROJECT_REF="\$existing_project"
        print_success "Using existing project: \$PROJECT_REF"
        ;;
      2)
        read -p "Enter new project name: " new_name
        create_new_supabase_project "\$new_name"
        return \$?
        ;;
      3)
        print_step "Cancelled by user"
        exit 1
        ;;
      *)
        print_error "Invalid choice"
        exit 1
        ;;
    esac
  else
    create_new_supabase_project "\$PROJECT_NAME"
  fi

  # Save project ref
  mkdir -p .supabase
  echo "\$PROJECT_REF" > .supabase/.project-ref

  mark_completed "supabase_project"
  print_success "Supabase project configured: \$PROJECT_REF"
}

create_new_supabase_project() {
  local proj_name="\$1"

  print_step "Creating new Supabase project: \$proj_name"

  # Get organization
  echo ""
  echo "Available organizations:"
  supabase orgs list
  echo ""
  read -p "Enter organization ID: " org_id

  if [[ -z "\$org_id" ]]; then
    print_error "Organization ID is required"
    exit 1
  fi

  # Get region
  echo ""
  echo "Available regions:"
  echo "  us-east-1      (N. Virginia)"
  echo "  us-west-1      (N. California)"
  echo "  eu-west-1      (Ireland)"
  echo "  eu-west-2      (London)"
  echo "  eu-central-1   (Frankfurt)"
  echo "  ap-southeast-1 (Singapore)"
  echo "  ap-southeast-2 (Sydney)"
  echo "  ap-northeast-1 (Tokyo)"
  echo ""
  read -p "Enter region (default: us-east-1): " region
  region=\${region:-us-east-1}

  # Generate a secure database password
  local db_password=\$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 20)

  # Create project
  echo ""
  print_step "Creating project (this may take 1-2 minutes)..."

  if supabase projects create "\$proj_name" --org-id "\$org_id" --region "\$region" --db-password "\$db_password" 2>/dev/null; then
    print_success "Supabase project created"

    # Wait for project to be ready
    print_step "Waiting for project to be ready..."
    sleep 30

    # Get project ref
    PROJECT_REF=\$(supabase projects list --json 2>/dev/null | jq -r ".[] | select(.name == \\"\$proj_name\\") | .id" 2>/dev/null || echo "")

    if [[ -z "\$PROJECT_REF" ]]; then
      print_warning "Could not automatically get project reference"
      echo ""
      echo "Please find your project reference at: https://supabase.com/dashboard"
      echo "Go to: Project Settings > General > Reference ID"
      read -p "Enter project reference: " PROJECT_REF
    fi
  else
    print_warning "Could not create project automatically"
    echo ""
    echo "This might happen if:"
    echo "  - You've reached your project limit"
    echo "  - The project name is already taken"
    echo "  - Invalid organization or region"
    echo ""
    echo "Please create a project manually at: https://supabase.com/dashboard"
    read -p "Enter the project reference ID: " PROJECT_REF
  fi

  if [[ -z "\$PROJECT_REF" ]]; then
    print_error "Project reference is required"
    exit 1
  fi
}

# =============================================================================
# Step 7: Link Supabase Project (skipped if USE_DOCKER=true)
# =============================================================================

link_supabase() {
  if [[ "\$USE_DOCKER" == "true" ]]; then
    print_step "Skipping Supabase linking (Docker mode)"
    return 0
  fi

  print_header "Linking Supabase Project"

  if [[ ! -f ".supabase/.project-ref" ]]; then
    print_error "No Supabase project configured"
    exit 1
  fi

  local project_ref=\$(cat .supabase/.project-ref)

  print_step "Linking to project: \$project_ref"
  supabase link --project-ref "\$project_ref"

  print_success "Supabase project linked"
}

# =============================================================================
# Step 8: Run Database Migrations (skipped if USE_DOCKER=true)
# =============================================================================

run_migrations() {
  if [[ "\$USE_DOCKER" == "true" ]]; then
    print_step "Skipping Supabase migrations (Docker mode)"
    return 0
  fi

  print_header "Running Database Migrations"

  if [[ ! -f ".supabase/.project-ref" ]]; then
    print_error "No Supabase project configured"
    exit 1
  fi

  local project_ref=\$(cat .supabase/.project-ref)

  print_step "Pushing schema to Supabase..."

  # Use drizzle-kit push to apply schema
  cd apps/web
  if pnpm db:push 2>/dev/null; then
    print_success "Database schema pushed successfully"
  else
    print_warning "Database push failed - you may need to run it manually"
    echo "  cd apps/web && pnpm db:push"
  fi
  cd ../..
}

# =============================================================================
# Step 9: Create/Link Vercel Project
# =============================================================================

setup_vercel() {
  print_header "Vercel Project Setup"

  # Check if already linked
  if [[ -f ".vercel/project.json" ]]; then
    print_success "Already linked to a Vercel project"
    return 0
  fi

  if is_completed "vercel_project"; then
    print_success "Vercel project already configured (from previous run)"
    return 0
  fi

  print_step "Setting up Vercel project..."
  echo ""
  echo "Vercel will prompt you to link or create a project."
  echo "Choose 'Set up and deploy' and follow the prompts."
  echo ""

  # Use vercel link without --yes to let user control decisions
  # This handles existing projects gracefully
  vercel link

  if [[ -f ".vercel/project.json" ]]; then
    mark_completed "vercel_project"
    print_success "Vercel project linked"
  else
    print_warning "Vercel project may not be fully configured"
  fi
}

# =============================================================================
# Step 10: Pull Vercel Environment Variables
# =============================================================================

pull_vercel_env() {
  print_header "Pulling Vercel Environment Variables"

  if [[ ! -f ".vercel/project.json" ]]; then
    print_warning "Vercel project not linked, skipping env pull"
    return 0
  fi

  print_step "Pulling environment variables from Vercel..."

  # Pull to apps/web/.env.local
  cd apps/web
  vercel env pull .env.local --yes 2>/dev/null || true
  cd ../..

  print_success "Environment variables pulled (if any were configured in Vercel)"
}

# =============================================================================
# Step 11: Populate .env.local with Supabase Credentials (skipped if USE_DOCKER=true)
# =============================================================================

populate_supabase_env() {
  if [[ "\$USE_DOCKER" == "true" ]]; then
    print_step "Skipping Supabase env configuration (Docker mode)"
    return 0
  fi

  print_header "Configuring Database Environment"

  if [[ ! -f ".supabase/.project-ref" ]]; then
    print_warning "No Supabase project configured, skipping"
    return 0
  fi

  local project_ref=\$(cat .supabase/.project-ref)
  local env_file="apps/web/.env.local"

  # Create env file from example if it doesn't exist
  if [[ ! -f "\$env_file" ]]; then
    if [[ -f "apps/web/.env.local.example" ]]; then
      cp "apps/web/.env.local.example" "\$env_file"
      print_step "Created .env.local from example"
    else
      touch "\$env_file"
    fi
  fi

  print_step "Fetching Supabase connection string..."

  # Get connection string from Supabase (uses the pooler connection)
  local db_url=\$(supabase db url --project-ref "\$project_ref" 2>/dev/null || echo "")

  if [[ -n "\$db_url" ]]; then
    # Update DATABASE_URL in .env.local
    if grep -q "^DATABASE_URL=" "\$env_file" 2>/dev/null; then
      # macOS sed syntax
      sed -i '' "s|^DATABASE_URL=.*|DATABASE_URL=\\"\$db_url\\"|" "\$env_file"
    else
      echo "DATABASE_URL=\\"\$db_url\\"" >> "\$env_file"
    fi
    print_success "DATABASE_URL configured"
  else
    print_warning "Could not fetch DATABASE_URL automatically"
    echo ""
    echo "Please add DATABASE_URL manually from:"
    echo "  https://supabase.com/dashboard/project/\$project_ref/settings/database"
    echo "  Use the 'Transaction' pooler connection string for serverless."
  fi
}

# =============================================================================
# Step 12: Final Summary
# =============================================================================

print_summary() {
  print_header "Setup Complete!"

  echo "Your project has been configured with:"
  echo ""

  # GitHub status
  if git remote get-url origin &> /dev/null 2>&1; then
    local repo_url=\$(git remote get-url origin)
    echo -e "  \${GREEN}✓\${NC} GitHub: \$repo_url"
  fi

  # Vercel status
  if [[ -f ".vercel/project.json" ]]; then
    echo -e "  \${GREEN}✓\${NC} Vercel: Project linked"
  fi

  # Supabase status (only if not Docker mode)
  if [[ "\$USE_DOCKER" != "true" ]]; then
    if [[ -f ".supabase/.project-ref" ]]; then
      local project_ref=\$(cat .supabase/.project-ref)
      echo -e "  \${GREEN}✓\${NC} Supabase: \$project_ref"
    fi
  else
    echo -e "  \${BLUE}→\${NC} Database: Docker (local)"
  fi

  echo ""
  echo "Next steps:"
  echo ""
  echo "  1. Review apps/web/.env.local and fill in any missing values:"
  if [[ "\$USE_DOCKER" != "true" ]]; then
    echo "     - RESEND_API_KEY (for email authentication)"
  fi
  echo "     - OPENAI_API_KEY or AI_GATEWAY_API_KEY"
  echo "     - NEXT_PUBLIC_POSTHOG_KEY (optional)"
  echo ""

  if [[ "\$USE_DOCKER" == "true" ]]; then
    echo "  2. Start the local database:"
    echo "     pnpm docker:up"
    echo ""
    echo "  3. Run migrations:"
    echo "     pnpm db:generate && pnpm db:migrate"
    echo ""
    echo "  4. Start development:"
    echo "     pnpm dev"
  else
    echo "  2. Start development:"
    echo "     pnpm dev"
  fi

  echo ""
  echo "  For deployment, configure environment variables in Vercel:"
  echo "     vercel env add DATABASE_URL"
  echo ""
}

# =============================================================================
# Main Execution
# =============================================================================

main() {
  echo ""
  echo "========================================"
  echo "       \$PROJECT_NAME Setup"
  echo "========================================"
  echo ""

  if [[ "\$USE_DOCKER" == "true" ]]; then
    echo "Mode: Docker (local PostgreSQL)"
  else
    echo "Mode: Supabase (cloud PostgreSQL)"
  fi
  echo ""

  check_prerequisites
  auth_github
  auth_supabase
  auth_vercel
  create_github_repo
  create_supabase_project
  link_supabase
  run_migrations
  setup_vercel
  pull_vercel_env
  populate_supabase_env
  print_summary
}

# Run main function
main "\$@"
`;
}
