export function generateSandboxSettings(): string {
	return JSON.stringify(
		{
			permissions: {
				disableBypassPermissionsMode: "disable",
				allow: [
					"Bash(pnpm lint:*)",
					"Bash(ls:*)",
					"Bash(pnpm test:*)",
					"Bash(pnpm typecheck:*)",
					"Bash(cat:*)",
					"Bash(pnpm --filter web typecheck:*)",
					"Bash(pnpm --filter web lint:*)",
					"Bash(pnpm --filter web test)",
					"Bash(nvm use)",
					"Bash(pnpm db:generate:*)",
					"Bash(find:*)",
					"Bash(xargs cat:*)",
					"Bash(pnpm --filter web test:*)",
					"Bash(node -e:*)",
					"Bash(node --input-type=module -e:*)",
					"Bash(grep:*)",
					"Bash(wc:*)",
					"Bash(paste:*)",
					"Bash(sort:*)",
					"Bash(git status:*)",
					"Bash(git diff:*)",
					"Bash(git log:*)",
					"Bash(git branch:*)",
					"Bash(git show:*)",
					"WebSearch",
				],
				deny: [],
				ask: [
					"Bash(git commit:*)",
					"Bash(git push:*)",
					"Bash(git merge:*)",
					"Bash(git rebase:*)",
					"Bash(git reset:*)",
					"Bash(git stash:*)",
					"Bash(git cherry-pick:*)",
				],
			},
		},
		null,
		"\t",
	);
}
